# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0442\u0441\u043e\u0432 \u0432\u0438\u0434\u0435\u043e\u043a\u0430\u0440\u0442')),
                ('avg', models.IntegerField(help_text='\u0421\u0440\u0435\u0434\u043d\u0438\u0439 \u043f\u043e\u043a\u0430\u0437\u0430\u0442\u0435\u043b\u044c \u0434\u043b\u044f \u0443\u043a\u0430\u0437\u0430\u043d\u043d\u043e\u0433\u043e \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u0430 \u0432\u0438\u0434\u0435\u043e\u043a\u0430\u0440\u0442', verbose_name='\u0421\u0440\u0435\u0434\u043d\u0438\u0439 \u043f\u043e\u043a\u0430\u0437\u0430\u0442\u0435\u043b\u044c')),
                ('variance', models.IntegerField(verbose_name='\u041e\u0442\u043a\u043b\u043e\u043d\u0435\u043d\u0438\u0435 %')),
            ],
        ),
        migrations.AlterField(
            model_name='machine',
            name='code',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name='\u0423\u043d\u0438\u043a\u0430\u043b\u044c\u043d\u044b\u0439 \u043a\u043e\u0434 \u043c\u0430\u0448\u0438\u043d\u044b'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='count',
            field=models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0442\u0441\u043e\u0432 \u0432\u0438\u0434\u0435\u043e\u043a\u0430\u0440\u0442'),
        ),
    ]
