# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_auto_20170815_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='count',
            field=models.IntegerField(unique=True, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0442\u0441\u043e\u0432 \u0432\u0438\u0434\u0435\u043e\u043a\u0430\u0440\u0442'),
        ),
    ]
